on: push
name: Build & Test
env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ex${{matrix.elixir}}/OTP${{matrix.otp}}
    strategy:
      matrix:
        include:
          - elixir: "1.15"
            otp: "25"
          - elixir: "1.18"
            otp: "27"
            lint: true
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test

      - name: checks that the mix.lock file has no unused deps
        run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - name: check if files are already formatted
        run: mix format --check-formatted
        if: ${{ matrix.lint }}
